name: SSO Requests - Request
author: SSO Team
description: Run 'Request' scripts using the GitHub client
branding:
  color: blue
  icon: code
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  api-url:
    description: The API url to update request status
    required: true
  auth-secret:
    description: The secret to authenticate the API request
    required: true
  tf-module-ref:
    description: The branch(ref) to pull the Terraform module from
    default: dev
    required: false
outputs:
  result:
    description: The return value of the script, stringified with `JSON.stringify`
runs:
  using: node12
  main: index.js
