name: SSO Requests - Keycloak
author: SSO Team
description: Run 'Keycloak' scripts using the GitHub client
branding:
  color: blue
  icon: code
inputs:
  dev-keycloak-url:
    description: The URL of the Keycloak instance in dev environment
    required: true
  test-keycloak-url:
    description: The URL of the Keycloak instance in test environment
    required: true
  prod-keycloak-url:
    description: The URL of the Keycloak instance in prod environment
    required: true
  dev-client-id:
    description: "The client_id for the Keycloak client in Master Realm in dev environment"
    required: false
    default: "terraform-cli"
  test-client-id:
    description: "The client_id for the Keycloak client in Master Realm in test environment"
    required: false
    default: "terraform-cli"
  prod-client-id:
    description: "The client_id for the Keycloak client in Master Realm in prod environment"
    required: false
    default: "terraform-cli"
  dev-client-secret:
    description: "The client_secret for the Keycloak client in Master Realm in dev environment"
    required: true
  test-client-secret:
    description: "The client_secret for the Keycloak client in Master Realm in test environment"
    required: true
  prod-client-secret:
    description: "The client_secret for the Keycloak client in Master Realm in prod environment"
    required: true
  tasks:
    description: "The tasks to run"
    required: true

outputs:
  result:
    description: true if succeed, false otherwise
runs:
  using: node12
  main: index.js
